name: CI
on: [push, pull_request]

concurrency: # Cancel stale PR builds (but not push builds)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache nimble packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - name: Install Nim
        uses: nim-lang/setup-nimble-action@v1
        with:
          nimble-version: '0.16.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build nph
        run: nimble build

      - name: Check formatting
        run: |
          ! ./nph --check tests/before
          ./nph --check tests/after

          ./nph src
          git diff --exit-code
